name: Excavator

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # run hourly

jobs:
  update-cursor:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install dependencies
        run: uv sync --locked

      - name: Run update script
        run: uv run scripts/update_cursor_bucket.py
